Portfolio desktop version
Sevenpros/Portfolio pull request #7
Opened 2022-06-02 12:16 UTC by Sevenpros

Add responsiveness for desktop devices
justify contents to fit well on the bigger screen
adjust font size and other element to fit screen.

2022-06-02 14:07 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Seth, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
GitHub flow is followed. :heavy_check_mark:
README is professional. :heavy_check_mark:
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
**_Note: Please do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-02 14:07 UTC, SajjadAhmad14 commented on index.html
>              <header class="about-header">
Please add a proper margin between `About me` and the horizontal line, and also between the `Languages` section and the horizontal line. Moreover, there should be only one horizontal line between the `About me` and `Languages` sections.

Yours:
![hori-you](https://user-images.githubusercontent.com/35504149/171647667-a645bc71-9c6d-4fb8-b4c3-17f6c5ddb760.png)

Design:
![hori-o](https://user-images.githubusercontent.com/35504149/171647713-4fe3b4d7-9ceb-4f71-a771-24315576a4bf.png)

2022-06-02 14:07 UTC, SajjadAhmad14 commented on index.html
> +            <div class="social-icons footer-icons">
Please use the same color for icons for the desktop version as defined in the design. The color is `#505F79`.

Yours:
![icons-you](https://user-images.githubusercontent.com/35504149/171647876-beebdf4b-8783-4222-973d-822816ec7e4e.png)

2022-06-02 14:07 UTC, SajjadAhmad14 commented on style.css
> +  .headline {
The background image of the headline is overlapping the text on the small mobile view. Kindly make sure that the mobile version works the same as expected and according to the design.

![back](https://user-images.githubusercontent.com/35504149/171647988-9182a805-6e69-42f3-a95f-0a3fcec34d7b.png)

2022-06-03 10:11 UTC, vic778 approved these changes
Hi @Sevenpros   , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Charlie Brown](https://media.giphy.com/media/ZdO4NenDbsQNwUwKDB/giphy.gif)

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification

2022-06-03 10:20 UTC, merged